### ISSUE TITLE
Serving XML

### ISSUE THREAD

**Issue by Mistborn94** [undecidables/COSBAS-Server#23]
Get the biometric controller to controller to serve xml files as  response to client requests - thymeleaf is supposed to be able to handle it but I can't figure it out.

I've looked in view resolvers and template resolvers a bit but haven't had any success.

**Comment by Mistborn94** [comment]
I got it working to serve plain text - so what is the preference? An XML template or plain text eg. JSON/XML created in Java?

**Comment by ghost** [comment]
Uhm either one is fine, which ever one works.

**Comment by Mistborn94** [comment]
Choice: We are going to use a library (I'm thinking google's GSON) to serialize the object to JSON and respond with plain text. The reason for the choice is that we will probably use JSON for the JavaScript Ajax requests and otherwise we are using two libraries for similar purposes.
