### ISSUE TITLE
Create Biometric Request

### ISSUE THREAD

**Issue by Mistborn94** [undecidables/COSBAS-Server#28]
Biometric Requests needs to be created from http request.

**Comment by ghost** [comment]
It can now create AccessRequest objects from http request. Please could you look through the code, made a small change to the AccessRequest object itself. Changed BiometricData[] to List<BiometricData>, think it will be easier to work with.

**Comment by Mistborn94** [comment]
Can you create a pull request from the correct branch that closes the issue?
