### ISSUE TITLE
Choose Calendar

### ISSUE THREAD

**Issue by Mistborn94** [undecidables/COSBAS-Server#42]
A staff member must be able to set their personal calendar.

**Comment by thepickpocket** [comment]
We will need a user interface (webpage) for this with a list of services the user can choose from. When a service has been chosen, then we can redirect so the user can authenticate COSBAS to use their data. I have an idea to make a page with images of services (Google, Microsoft Outlook etc) and just disable the links on those services not yet supported to show that COSBAS is highly plugable for use with other services.

**Comment by Mistborn94** [comment]
I think it is a good idea to fetch the available calendar types from the
system instead of hard coding it  in the interface. Its better for
maintainability.

**Comment by thepickpocket** [comment]
Yeah I just thought it would look good for demonstration purposes, but your idea would work better in production.

**Comment by thepickpocket** [comment]
The page "chooseService" needs to be styled according to the theme being used over the project.
