### ISSUE TITLE
Register User

### ISSUE THREAD

**Issue by Mistborn94** [undecidables/COSBAS-Server#46]
Register a user on the biometric system

**Comment by Mistborn94** [comment]
Just need to make sure client and server integrates 100% for this before closing it.

**Comment by VivianLVenter** [comment]
I also need to still add the fingerprint registration I am just waiting for them to sort out the issues they have...

**Comment by Mistborn94** [comment]
I'm closing this, since server side registration is complete. We can add a new issue to the client to capture the fingerprint and send it too the server.
