### ISSUE TITLE
Create Databse

### ISSUE THREAD

**Issue by Mistborn94** [undecidables/COSBAS-Server#6]
Create and host an database so we all use the same one. MongoDB?

**Comment by ghost** [comment]
I can make us one :) sometime on the weekend

**Comment by Mistborn94** [comment]
So assign yourself....

**Comment by ghost** [comment]
Yes mam! :P

**Comment by ghost** [comment]
Mongo DB is up and running.
Address: 45.55.178.39
User: 301testing
Password: 301t3st1ng
