### ISSUE TITLE
Change AuthenticationKey in DB

### ISSUE THREAD

**Issue by VivianLVenter** [undecidables/COSBAS-Server#65]
I need to sort out where we should put it and how we will be doing it.

**Comment by Mistborn94** [comment]
I think it should be a separate collection, associated with a personID (Mongo DB id, probably easiest) and valid for 'always' or a specified time frame.

**Comment by VivianLVenter** [comment]
Yip I thought about it, it can work then we have better control over the expiry of the key. Will do this after the meeting this afternoon.

**Comment by VivianLVenter** [comment]
@Babalela01 Should we not close this or is this still an issue?

**Comment by Mistborn94** [comment]
Oh, I must have missed this one :)
