### ISSUE TITLE
Create Wiki

### ISSUE THREAD

**Issue by Mistborn94** [undecidables/COSBAS-Server#8]
We need to create the wiki and start writing stuff in it.

**Comment by VivianLVenter** [comment]
Jason likes to do stuff like this, so when he has time he can create and start it...
You do not have to write everything...

**Comment by thepickpocket** [comment]
Awesome :D I will get to it right away :dash:

**Comment by VivianLVenter** [comment]
I think we can move this to done? Since it is created... We can create issues when we have to add stuff...

**Comment by thepickpocket** [comment]
I agree...will move it now
