### ISSUE TITLE
Wrong Password Notification

### ISSUE THREAD

**Issue by thepickpocket** [undecidables/COSBAS-Server#89]
When a wrong password is entered, there is no feedback as to what went wrong, the login page is simply reloaded. I think it would be good to add a notification message stating that login failed due to bad credentials.

**Comment by thepickpocket** [comment]
The errors that occured on server now is being displayed, but elementary stuff like "Wrong username and password" is stated too complex for an end-user, maybe just update the message for this?

**Comment by Elzahn** [comment]
Already tried that but you saw today it worked on Szymon's pc need to figure out why

**Comment by Elzahn** [comment]
Think I found a way to force the error hope no other errors were broken
